### ISSUE TITLE
"command not found: go-ipfs" even though ipfs is installed

### ISSUE THREAD

**Issue by atharvashukla** [yusefnapora/minty#23]
I cloned the repository, and ran `./start-local-environment.sh`, and I get the following error:

```
[eth] ...
[eth] ...
[eth] ...
[ipfs] npx: command not found: go-ipfs
[ipfs] npx go-ipfs daemon exited with code 127
```

*Note*: I have already downloaded and installed from go-ipfs from the [ipfs distributions page](go-ipfs). I have also installed via npm `npm install -g go-ipfs`

Any idea why this is occurring and how I might be able to fix it?

Update: Changing line 17 in the `start-local-environment.sh ` script from `run_ipfs_cmd="npx go-ipfs daemon"` to `run_ipfs_cmd="ipfs daemon"` launches the daemon.

**Comment by JamesVitaly** [comment]
Bump - getting this issue to - exactly as above. Any ideas?
